name: zmab
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3

  # UI & Responsive
  flutter_screenutil: ^5.9.3

  # Images
  image_picker: ^1.1.2
  image: ^4.1.7   # Compresión / manejo de imágenes

  # Sharing
  share_plus: ^7.2.1

  # Permissions
  permission_handler: ^11.3.1

  # Device Info
  device_info_plus: ^10.1.0

  # Utils
  uuid: ^4.4.0
  intl: ^0.20.2

  # PDF & File handling
  pdf: ^3.10.4
  open_filex: ^4.5.0
  printing: ^5.11.1

  # File picker
  file_picker: ^8.0.3

  # Cryptography
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Hive code generation
  hive_generator: ^2.0.1
  build_runner: ^2.5.4

  # App Icon Generator
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/logo.png"
  remove_alpha_ios: true
  adaptive_icon_padding: 10

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icon/
